### ISSUE TITLE
Doesn't commit

### ISSUE THREAD

**Issue by Epikest** [JohnnyMorganz/stylua-action#36]
this is my workflow.yml
```yml
on:
  push:
    branches:
    - main

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: JohnnyMorganz/stylua-action@1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --verify -g '*.lua' -g '*.iy' -- .

    - uses: EndBug/add-and-commit@v9
      with:
        add: "."
        committer_name: GitHub Actions
        committer_email: actions@github.com
```
it works if i run the command `stylua --verify -g '*.lua' -g '*.iy' -- .` locally but not in GitHub actions

**Comment by JohnnyMorganz** [comment]
Sounds like an issue with your commit action.

Does the commit action also run git push?

Here's an existing action which works correctly, maybe that will help: https://github.com/L3MON4D3/LuaSnip/blob/master/.github/workflows/push.yaml

**Comment by Epikest** [comment]
i don't think the commit action is causing the issue

> Sounds like an issue with your commit action.
> 
> Does the commit action also run git push?
> 
> Here's an existing action which works correctly, maybe that will help: [https://github.com/L3MON4D3/LuaSnip/blob/master/.github/workflows/push.yaml](https://github.com/L3MON4D3/LuaSnip/blob/master/.github/workflows/push.yaml?rgh-link-date=2022-06-29T19%3A42%3A31Z)

this works but it takes a long time to compile
```yml
on:
  push:
    branches:
    - main

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: download-and-format
      run: |
        cargo install stylua --features luau
        stylua --verify -g '*.lua' -g '*.iy' -- .

    - uses: EndBug/add-and-commit@v9
      with:
        add: "."
        committer_name: GitHub Actions
        committer_email: actions@github.com
```

quick side question, is there a way to treat files as if they have a different extension?
i want `*.iy` files to be treated as `*.luau`
