### ISSUE TITLE
[question] how to push commit back after stylua workflow

### ISSUE THREAD

**Issue by shikulja** [JohnnyMorganz/stylua-action#51]
i use simple congfig, but I can’t figure out how to return the formatted code to Github

```
name: Stylua check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "rework" ]
  pull_request:
    branches: [ "rework" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: stylua
      uses: JohnnyMorganz/stylua-action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
        args: -g '*.lua' -- .
```

run command give error. code 2
