### ISSUE TITLE
Feature Request: Allow install+cache-only mode

### ISSUE THREAD

**Issue by ColinKennedy** [JohnnyMorganz/stylua-action#57]
I'd like to use this action because it installs stylua and caches it. After that, the action would end, leaving me with an installed (or cached) stylua that I can then run myself.

A thought on how that could look:

```yaml
- uses: actions/checkout@v4
- uses: JohnnyMorganz/stylua-action@v4
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
    # CLI arguments
    args: false
```

When args is false, don't call 

```ts
await exec(`stylua ${args}`)
``` 
and just end
