### ISSUE TITLE
Nothing changed without --checked parameter

### ISSUE THREAD

**Issue by Kaiser-Yang** [JohnnyMorganz/stylua-action#59]
When with `--checked` it will output the diff. But I want to write directly to the files, so I removed the parameter and use `git-auto-commit-action` to commit the changes, here is my `workflow` file:

```yaml
name: formatter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  stylua:
    name: Format Lua Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --verify -g '*.lua' -- .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "format: stylua"
```

But this gives me `there is nothing changed`.

[ci](https://github.com/Kaiser-Yang/blink-cmp-git/actions/runs/13068095300)

**Comment by grayespinoza** [comment]
Assuming you want to keep the `.lua'` behavior, your arguments are fine except `--verify`. Remove it and it'll result in actual formatting, but you'll face a problem with `git-auto-commit-action`. You need to add `permissions: contents: write` to `Format Lua Files`, so that the action can actually write to the files.

**Comment by Kaiser-Yang** [comment]
I've updated as your suggestions. But now it fails when running auto commit:

[ci](https://github.com/Kaiser-Yang/blink-cmp-git/actions/runs/13962035158/job/39085002261?pr=8)

```lua
name: formatter

on:
  pull_request:
    branches:
      - master

jobs:
  stylua:
    name: Format Lua Files
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: format
```

**Comment by grayespinoza** [comment]
For `pull_request` events, which is now your only event, you need to also specify the ref`${{ github.head_ref }}`.
```yaml
- name: Checkout
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref }}
```
